### ISSUE TITLE
Devise

### ISSUE THREAD

**Issue by raphaelmonnard** [fablab-iciautour/fab-manager#6]
Lors de la création d'une facture, la notification et mail est en euro

-> changer en franc suisse

**Comment by ioknox** [comment]
Je ne sais pas d'ou cela vient. Sur ma machine parfois c'est en Euro, parfois en CHF.

**Comment by ioknox** [comment]
Tous les paramètres possible sont en CHF en tout cas

**Comment by ioknox** [comment]
Duplicate of #3
