### ISSUE TITLE
Réinitialisation mot de passe

### ISSUE THREAD

**Issue by raphaelmonnard** [fablab-iciautour/fab-manager#7]
Jean-Sébastien Terradillos:

'ai essayé de réinitialisé mon mot de passe via le formulaire et tout, mais le lien de l'email reçu ne fonctionne pas (renvoit à la page d'accueil).

**Comment by ioknox** [comment]
J'ai essayé avec mon compte et cela marche. Tu as reçu cette info par mail ?

**Comment by ioknox** [comment]
Comment je le contacte ?

**Comment by ioknox** [comment]
Cas clos car logiciel de protection enlevait le token de l'URL
