### ISSUE TITLE
Inscription

### ISSUE THREAD

**Issue by raphaelmonnard** [fablab-iciautour/fab-manager#9]
De Roman: 

Hello, Je voulais m'inscrire mais le bouton "valider" ne s'est pas laisser valider. Les boutons "plus d'info" selon screen shot ne veulent pas non plus se laisser faire. Sur cette page: https://fablab-chaux-de-fonds.ch/#!/plans Je réessaierai dans qque jours, ce n'est pas pressant. A++ Roman

**Comment by ioknox** [comment]
Peux-tu uploader le screenshot ? C'est lui l'utilisateur avec un IPhone ancien ?
